name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-test:
    name: ESLint and npm test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Run tests
        run: npm test

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Codespell
        uses: codespell-project/actions-codespell@v2