name: Lint

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 'lts/*'
      - name: Install modules
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'

  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Run Codespell
        uses: codespell-project/actions-codespell@v2
